# Do-It-Yourself {#sec-map-raster-DIY .unnumbered}


## Option 1

Working on a time-series representation of the evolution of Nights Lights in a **country of your choice**. As in the lab, the data can be found [here](https://www.ngdc.noaa.gov/eog/data/web_data/v4composites/).

1.  Process the data and make a map with at least two years of night lights data.
2.  Think about the story the data is telling you.
    -   How have night lights evolved over time in your country of choice? Remember this will mean different things for different countries.

    -   What choices have you made in terms of bins, colours, zoom level to tell your story?

<iframe src="https://ourworldindata.org/grapher/share-of-the-population-with-access-to-electricity" loading="lazy" style="width: 100%; height: 600px; border: 0px none;"></iframe>

## Option 2

Introducing [NASA's Black Marble dataset](https://yohaniddawela.substack.com/p/not-all-nightlight-datasets-are-the)

### Following the Tutorial Downloading and processing Black Marble nightlights data in R

https://yohaniddawela.substack.com/p/tutorial-downloading-and-processing

### Tutorial: How to increase the resolution of nightlights data

The exact steps and codebase to increase nightlights from ~500m to ~30m resolution